# Trigger Key
TriggerKey=
# Paste Primary
PastePrimaryKey=
# Number of entries
Number of entries=5
# Do not show password from password managers
IgnorePasswordFromPasswordManager=True
# Display passwords as plain text
ShowPassword=True
# Seconds before clearing password
ClearPasswordAfter=180

