## ================================================
##   _   ____  ______  _  _______  _  ___________
##  | | / / / / / __ \/ |/ / ___/ / |/ / ___/ __ \
##  | |/ / /_/ / /_/ /    / (_ / /    / (_ / /_/ /
##  |___/\____/\____/_/|_/\___/ /_/|_/\___/\____/
## ================================================

# --- General Settings ---
# Change Prefix from Ctrl+b to Ctrl+a (Easier to reach)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable mouse support
set -g mouse on
set -g set-clipboard on
set -g status-position top

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

# Automatically renumber windows when one is closed
set -g renumber-windows on

# Set number-windows is 1
set -g base-index 1
setw -g pane-base-index 1

# Fix escape time delay (Crucial for Neovim)
set -s escape-time 0

# --- VIM-Style Navigation & Controls ---
# 1. Use Vim keybindings in Copy Mode
# Press Prefix + [ to enter copy mode
setw -g mode-keys vi
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi a send-keys -X clear-selection
bind-key -T copy-mode-vi i send-keys -X clear-selection

bind v copy-mode
bind c kill-pane
bind B new-session
bind b new-window -c "#{pane_current_path}"

# Move new-session
bind ( switch-client -p
bind ) switch-client -n

# Use 'v' to begin selection and 'y' to yank (copy)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Move
bind-key -T copy-mode-vi u send-keys -X halfpage-up
bind-key -T copy-mode-vi d send-keys -X halfpage-down

bind-key -T copy-mode-vi w send-keys -X next-word
bind-key -T copy-mode-vi b send-keys -X previous-word
bind-key -T copy-mode-vi e send-keys -X end-of-word

# 3. Resize Panes using H, J, K, L (Prefix + Shift + h/j/k/l)
# -r flag allows repeatable key presses without hitting Prefix again
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# --- Custom Bindings ---
# Split windows using | and -
# Ensures new panes open in the current working directory
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Quick pane switching using Alt + h/j/k/l (No Prefix required)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Reload configuration file
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config!"

# --- Appearance (UI) ---
# Status bar colors
set -g status-justify left
set -g status-style "bg=default"

set -g status-left-length 100
set -g status-left "#{?client_prefix,#[fg=#ff9e64]#[bg=default]#[bg=#ff9e64]#[fg=#000000]#[bold]  PREFIX #[fg=#ff9e64]#[bg=default]#[nobold],#{?pane_in_mode,#[fg=#bb9af7]#[bg=default]#[bg=#bb9af7]#[fg=#000000]#[bold]  VISUAL #[fg=#bb9af7]#[bg=default]#[nobold],#[fg=#ffffff]#[bg=default]#[bg=#ffffff]#[fg=#000000]#[bold]  NORMAL #[fg=#ffffff]#[bg=default]#[nobold]}} "

set -g status-right-length 100
set -g status-right "#[fg=#ffffff,bg=default]#[bg=#ffffff,fg=#000000,bold]  %H:%M #[fg=default,bg=default]"

set -g window-status-current-format "#[fg=#ffffff,bold] #I: #W "
set -g window-status-format "#[fg=#787c87] #I: #W "
set -g window-status-separator " "
